# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Bellvenor.Pouncify
PackageVersion: 0.0.127
InstallerType: nullsoft
Scope: user
InstallModes:
  - silent
  - silentWithProgress
  - interactive
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
  InstallLocation: /D=<INSTALLPATH>
UpgradeBehavior: install
Protocols:
  - pouncify
ProductCode: 2443e90b-35a8-581b-9a01-b3fd52b02c6f
AppsAndFeaturesEntries:
  - DisplayVersion: 0.0.127
    Publisher: Bellvenor LLC
    ProductCode: 2443e90b-35a8-581b-9a01-b3fd52b02c6f
    InstallerType: nullsoft
MinimumOSVersion: 10.0.0.0
ReleaseDate: 2026-10-10
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/bellvenor/pouncify-releases/releases/download/v0.0.127/Pouncify-Setup-0.0.127.exe
    InstallerSha256: 744A1A1873AA85A65DFE57C0365ED672CA77EA875872C197415F2684CA03EABE
ManifestType: installer
ManifestVersion: 1.12.0
